### ISSUE TITLE
Missing sinusoidal component on a few voices

### ISSUE THREAD

**Issue by tuxzz** [Sleepwalking/libllsm#3]
Original:
https://mega.nz/#!PkEjwYIT!5BHf2k4ohTx7YS19x3mc3-7hgslxMW26qSbA-fbSZmA

Resynthed:
https://mega.nz/#!P0cyFRoJ!isqnaHoRt5HfmWtjyvtrTc3EwwPFSk6rU8SFt4Nkzsk

Voice source: Gakkou Gurashi VOL1

**Comment by Sleepwalking** [comment]
Missing sinusoids in the last syllable is caused by a U/V detection error in `libpyin`. For breathy voice you can raise `bias` in `pyin_parameters` to reduce true negative (at the risk of having more false positives).
