### ISSUE TITLE
How to install in mac ?

### ISSUE THREAD

**Issue by velmurugansubramaniam2** [Sleepwalking/libllsm#5]
Hi , Can you please provide a steps , How to compile test application in mac / Fedora?

**Comment by Sleepwalking** [comment]
Hi, please get [_libpyin_](https://github.com/Sleepwalking/libpyin) and [_libgvps_](https://github.com/Sleepwalking/libgvps) first. Put _libpyin_ under `external/` and nest _libgvps_ under `external/libpyin/external/`. Then cd into the innermost library (which is _libgvps_) and recursively compile them.
